### PR TITLE
TextStyle and onReset event...

### PR DESCRIPTION
**Pull request by caledhwa**
In order to style the text specifically, I added a textStyle property and appropriate documentation. This allows me to continue to use your messaging functionality while using custom fonts, bold, size, etc. 

In addition, I noticed that after the interval, the right/wrong message persisted until you touch the circles again. I added an onReset event so you could assign a function to it to reset the message, navigate, etc. 

Hopefully, you'll merge this!!! Would be cool to get your library into my sample app. Also, if you'd like me to make a change of what I did, let me know. This library has lots of potential for what I want to use it for.

### CODE REVIEW

**Comment by caledhwa** [comment]
Bump @Spikef ... :-)

**Comment by caledhwa** [comment]
Hey! No problem! Good stuff. Thanks for the merging. If I come up with other ideas, I'll see what I can contribute. Very nice project. Does exactly what I needed!

**Comment by caledhwa** [comment]
Hey @Spikef - any way we could publish this to NPM as version 0.1.5? I'd like to use it in my project without a direct reference. Unless you have some changes you want to make for a next version... Let me know.

**Comment by Spikef** [comment]
@caledhwa v0.1.5 is available on NPM now!

**Comment by caledhwa** [comment]
You are a king @spikef!



On April 8, 2016 at 6:24:40 AM, Spikef (notifications@github.com) wrote:

@caledhwa v0.1.5 is available on NPM now!

**Pull request merged**
