### PR TITLE
allow no border

### PR DESCRIPTION
**Pull request by mvayngrib**
added `hollow` boolean property, when false it looks like this:
simulator screen shot jan 28 2016 9 14 13 am

simulator screen shot jan 28 2016 9 13 16 am

### CODE REVIEW

**Comment by Spikef** [comment]
I'll export a style property to meet more custom stylish.

**Comment by mvayngrib** [comment]
@Spikef great, thanks

**Comment by caledhwa** [comment]
+1 to an exported style property for this. It will allow colorization specific to the circles -> very nice.

**Comment by Spikef** [comment]
Sorry for the delay. I add two properties `outerCircle` and `innerCircle` to allow no outer circle or no inner circle. So I'll close this PR. Thank you very much.

**Pull request closed without merging**
